DndMagicLibrary/Models/DndClass.cs
using DndMagicLibrary.Data;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace DndMagicLibrary.Models
{
    public class DndClass : IDndClass
    {
        public DndClass() { }

        public string Name { get; set; }
        public int GeneralIndex { get; set; }
        public int SpellcastingIndex { get; set; }
        public string Description { get; set; }
        public int Hit_Die { get; set; }
        [JsonProperty("spellcasting")]
        public SpellCasting SpellCasting { get; set; }

        [JsonIgnore]
        public Dictionary<int, IEnumerable<string>> Spells { get; set; }

        public DndClass(string name)
        {
            Name = name;
            Description = AllClasses.DndClasses.Where(x => x.Name == name).FirstOrDefault().Description;
            GeneralIndex = AllClasses.DndClasses.Where(x => x.Name == name).FirstOrDefault().GeneralIndex;
            SpellcastingIndex = AllClasses.DndClasses.Where(x => x.Name == name).FirstOrDefault().SpellcastingIndex;
        }

        public DndClass(string name, string description, int generalIndex, int spellcastingIndex)
        {
            Name = name;
            Description = description;
            GeneralIndex = generalIndex;
            SpellcastingIndex = spellcastingIndex;
        }
    }
}

DndMagicLibrary/Models/IDndClass.cs
using System.Collections.Generic;

namespace DndMagicLibrary.Models
{
    public interface IDndClass
    {
        int GeneralIndex { get; set; }
        int SpellcastingIndex { get; set; }
        string Name { get; set; }
        string Description { get; set; }
        int Hit_Die { get; set; }
        SpellCasting SpellCasting { get; set; }
        Dictionary<int, IEnumerable<string>> Spells { get; set; }
    }
}

DndMagicLibrary/Models/ISpell.cs
using System.Collections.Generic;

namespace DndMagicLibrary.Models
{
    public interface ISpell
    {
        string Name { get; set; }
        string Url { get; set; }
        int Level { get; set; }
        IEnumerable<string> Description { get; set; }
        IEnumerable<string> Components { get; set; }
        string Range { get; set; }
        string Material { get; set; }
        bool Ritual { get; set; }
        string Duration { get; set; }
        bool Concentration { get; set; }
        string CastingTime { get; set; }
        School School { get; set; }
    }
}

DndMagicLibrary/Models/School.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DndMagicLibrary.Models
{
    public class School
    {
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

DndMagicLibrary/Models/Spell.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace DndMagicLibrary.Models
{
    public class Spell : ISpell
    {
        public string Name { get; set; }
        public string Url { get; set; }
        public int Level { get; set; }
        [JsonProperty("desc")]
        public IEnumerable<string> Description { get; set; }
        public IEnumerable<string> Components { get; set; }
        public string Range { get; set; }
        public string Material { get; set; }
        public bool Ritual { get; set; }
        public string Duration { get; set; }
        public bool Concentration { get; set; }
        [JsonProperty("casting_time")]
        public string CastingTime { get; set; }
        public School School { get; set; }

        public string ConvertSpellName(string name)
        {
            var splitUpName = name.ToLower().Split(' ');
            var validatedName = RemoveNames(splitUpName);
            return string.Join("-", validatedName);
        }

        public IEnumerable<string> RemoveNames(string[] splitUpName)
        {
            // We need to remove names like Mordekainen's and Otto's
            return splitUpName.Where(x => !x.Contains("'s"));
        }
    }
}

DndMagicLibrary/Models/SpellCasting.cs
using Newtonsoft.Json;

namespace DndMagicLibrary.Models
{
    public class SpellCasting
    {
        public string Url { get; set; }
        public string Class { get; set; }
        public string Name { get; set; }
        public int Index { get; set; }
        [JsonProperty("spellcasting_ability")]
        public SpellcastingAbility SpellcastingAbility { get; set; }
    }
}

DndMagicLibrary/Models/SpellCastingAbility.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DndMagicLibrary.Models
{

    public class SpellcastingAbility
    {
        public string Url { get; set; }
        public string Name { get; set; }
    }
}

DndMagicLibrary/Controllers/ClassController.cs
using DndMagicLibrary.Data;
using DndMagicLibrary.Data.Api;
using DndMagicLibrary.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DndMagicLibrary.Controllers
{
    [RoutePrefix("Class")]
    public class ClassController : Controller
    {
        IApiHelper _helper;
        public ClassController(IApiHelper helper)
        {
            _helper = helper;
        }

        public ActionResult Index()
        {
            return View();
        }

        [Route("/{id}")]
        public async Task<ActionResult> ShowClass(string id)
        {
            var dndClass = new DndClass(id);
            var newModel = await _helper.GetClassData(dndClass);
            newModel.Spells = GetSpellNames(dndClass.Name);
            return View(newModel);
        }

        private Dictionary<int, IEnumerable<string>> GetSpellNames(string dndClass)
        {
            var spellList = new ClassSpellLists();
            switch (dndClass.ToLower())
            {
                case "bard": return spellList.GetBardSpells();
                case "cleric": return spellList.GetClericSpells();
                case "druid": return spellList.GetDruidSpells();
                case "paladin": return spellList.GetPaladinSpells();
                case "ranger": return spellList.GetRangerSpells();
                case "sorcerer": return spellList.GetSorcererSpells();
                case "warlock": return spellList.GetWarlockSpells();
                case "wizard": return spellList.GetWizardSpells();
                default: return null;

            }
        }
    }
}

DndMagicLibrary/Controllers/HomeController.cs
using DndMagicLibrary.Data;
using System.Web.Mvc;

namespace DndMagicLibrary.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View(AllClasses.DndClasses);
        }
    }
}

DndMagicLibrary/Controllers/SpellController.cs
using DndMagicLibrary.Data.Api;
using DndMagicLibrary.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DndMagicLibrary.Controllers
{
    public class SpellController : Controller
    {
        IApiHelper _helper;

        public SpellController(IApiHelper helper)
        {
            _helper = helper;
        }
        // GET: Spell
        [Route("/{id}")]
        public async Task<ActionResult> Spell(string id)
        {
            var spell = new Spell { Name = id };
            var apiName = spell.ConvertSpellName(id);
            return View(await _helper.GetSpellData(apiName));
        }
    }
}

DndMagicLibrary/Views/Class/Bard.cshtml
@model DndMagicLibrary.Models.DndClass
<link rel="stylesheet" href="~/Scripts/bootstrap.min.js" />

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name.ToUpper()</h2>

<p>This is a page about the @Model.Name class.</p>
<p>@Model.Description</p>
<p>The @Model.Name's Hit Die is @Model.Hit_Die</p>

<h2 class="text-center">Click on a level for spell details</h2>
<div class="btn btn-default">@Html.ActionLink("1", "Spell", "1")</div>
<div class="btn btn-default">@Html.ActionLink("2", "Spell", "2")</div>
<div class="btn btn-default">@Html.ActionLink("3", "Spell", "3")</div>
<div class="btn btn-default">@Html.ActionLink("4", "Spell", "4")</div>
<div class="btn btn-default">@Html.ActionLink("5", "Spell", "5")</div>
<div class="btn btn-default">@Html.ActionLink("6", "Spell", "6")</div>
<div class="btn btn-default">@Html.ActionLink("7", "Spell", "7")</div>
<div class="btn btn-default">@Html.ActionLink("8", "Spell", "8")</div>
<div class="btn btn-default">@Html.ActionLink("9", "Spell", "9")</div>


<h2 class="text-center">Click below for more information about the @Model.Name's spellcasting</h2>
@Html.ActionLink("Spellcasting", "GetSpellcastingData")

DndMagicLibrary/Views/Class/ShowClass.cshtml
@model DndMagicLibrary.Models.DndClass
<script src="~/Scripts/bootstrap.bundle.min.js"></script>

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name.ToUpper()</h2>

<p>This is a page about the @Model.Name class.</p>
<p>@Model.Description</p>
<p>The @Model.Name's Hit Die is @Model.Hit_Die</p>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    @if (Model.Spells.ContainsKey(0))
    {
        <li class="nav-item">
            <a class="nav-link active" id="pills-0-tab" data-toggle="pill" href="#pills-0" role="tab" aria-controls="pills-0" aria-selected="true">Cantrips</a>
        </li>
    }
    @for (var i = 1; i < Model.Spells.Count; i++)
    {
        <li class="nav-item">
            <a class="nav-link" id="pills-@i-tab" data-toggle="pill" href="#pills-@i" role="tab" aria-controls="pills-@i" aria-selected="true">Level @i</a>
        </li>
    }
</ul>
<div class="tab-content" id="pills-tabContent">
    @if (Model.Spells.ContainsKey(0))
    {
        <div class="tab-pane fade show active" id="pills-0" role="tabpanel" aria-labelledby="pills-0-tab">
            <ul>
                @foreach (var spell in Model.Spells[0])
                {
                    <li>@Html.ActionLink(spell, "Spell", "Spell", new { id = spell }, null)</li>
                }
            </ul>
        </div>
    }
    @for (var i = 1; i < Model.Spells.Count; i++)
    {
        <div class="tab-pane fade" id="pills-@i" role="tabpanel" aria-labelledby="pills-@i-tab">
            <ul>
                @foreach (var spell in Model.Spells[i])
                {
                    <li>@Html.ActionLink(spell, "Spell", "Spell", new { id = spell }, null)</li>
                }
            </ul>
        </div>
    }
</div>

DndMagicLibrary/Views/Home/Index.cshtml
@model List<DndMagicLibrary.Models.DndClass>
@{
    ViewBag.Title = "D&D Magic Library";
}

<div class="jumbotron my-2">
    <h1>D&D Magic Library</h1>
    <p class="lead">This application will display D&D spells by class and level.</p>
    <p>It uses the <a href="http://www.dnd5eapi.co/" class="btn btn-primary btn-lg">D&D API</a></p>
</div>

<h1 class="text-center my-4 btn-outline-info">D&D Spellcasting Classes</h1>
<div class="row">
    @foreach (var myModel in Model)
    {
        <div class="col-md-3 py-2">
            <div class="card">
                <h5 class="card-title text-center text-uppercase bg-info py-3">@myModel.Name</h5>
                <div class="card-body">
                    <p class="card-text">@String.Join("", Model.Where(x => x.Name == myModel.Name).Select(x => x.Description))</p>
                    <div class="text-center">
                        <button class="text-center btn btn-light border-dark">@Html.ActionLink($"See {@myModel.Name} Class", "ShowClass", "Class", new { id = @myModel.Name }, null)</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

DndMagicLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - D&D Magic Library</title>
    <link rel="stylesheet" href="~/Scripts/bootstrap.min.js" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap" rel="stylesheet">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="~/Views/Home/Index.cshtml">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container body-content medieval-sharp">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - D&D Magic Library</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DndMagicLibrary/Views/Spell/Spell.cshtml
@model DndMagicLibrary.Models.Spell
@{
    ViewBag.Title = "D&D Magic Library";
}

<link href="https://fonts.googleapis.com/css2?family=Tangerine:wght@700&display=swap" rel="stylesheet">

<h1 class="text-center my-4 btn-outline-info">Behold the @Model.Name spell!</h1>
<div class="parchment tangerine">
    <div class="container mx-4">
        <div style="padding: 80px">
            <div><strong>Name:</strong> @Model.Name</div>
            <div>
                <strong>Description:</strong>
                @foreach (var description in @Model.Description)
                {
                    <div>- @description</div>
                }
            </div>
            <div><strong>Range:</strong> @Model.Range</div>
            <div>
                <strong>Components:</strong>
                @foreach (var component in Model.Components)
                {
                    <span>@component</span>
                }
            </div>
            <div><strong>Casting Time:</strong> @Model.CastingTime</div>
            <div><strong>School:</strong> @Model.School.Name</div>
        </div>
    </div>
</div>